### PR TITLE
Added unit test and Python 2 compatibility

### PR DESCRIPTION
**Pull request by ZuluPro**
Hello @danni ,
Thank for this project,

Added a `.gitignore` file
Added Python 2 compatibility
Added unit test with testapp and settings
Added a test runner script at root
Update CI for use tests

### CODE REVIEW

**Comment by danni** [comment]
Hey thanks for this PR. Tests are much appreciated. One ask though, can you do the py2 compatibility with python-future instead. That way it will be easier to remove in the future. Thanks!

**Comment by ZuluPro** [comment]
@danni That's done !
I plan to check if this is compatible with most versions of Django >= 1.6 and Python >= 2.7.
I'll use it with [django-dbbackup](https://github.com/django-dbbackup/django-dbbackup) and must support versions as more as possible for help users' upgrades.
I think python-future is real plus for that !

**Comment by ZuluPro** [comment]
@danni Any news ?

**Comment by danni** [comment]
My apologies, I'd reviewed this on my phone previously and my github email keeps going randomly missing. This is great. Thanks!

**Comment by danni** [comment]
I'll pull the tox config from https://github.com/danni/django-postgres-composite-types to test a combination of Python/Django versions today.

**Pull request merged**
